#!/bin/bash
# Updates `content/reference/api/cli.md` from the locally installed go-ipfs

exec &> ./content/reference/api/cli.md

echo "---
title: \"CLI Commands\"
identifier: clicommands
weight: 10
menu:
    reference:
        parent: api
beta_equivalent: reference/cli
---

# CLI commands

This document is autogenerated from [scripts/cli.sh](https://github.com/ipfs/docs/blob/master/scripts/cli.sh). For issues and support, check out the [docs repository](https://github.com/ipfs/docs) on GitHub.

echo "*Generated on $(date +"%Y-%m-%d %T"), from go-ipfs $(ipfs version -n).*"
printf "\n"
ipfs commands | while read line ; do
  echo "- [$line](#$(echo $line | tr -s ' ' -))"
done
printf "\n"
ipfs commands | while read line ; do
  printf "## $line\n\n\`\`\`\n"
  $line --help
  printf "\`\`\`\n\n"
done
